---
- name: Nginx Install
  hosts: web
  become: true
  gather_facts: true

  tasks:
    - name: EC2 Nginx install
      yum:
        name: nginx
        state: present 

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started 

- name: JDK Install
  hosts: app
  become: true
  gather_facts: true

  tasks:
    - name: Clean dnf metadata/cache
      command: dnf clean all
      changed_when: false

    - name: Rebuild dnf cache
      command: dnf makecache
      changed_when: false

    - name: Install OpenJDK 17
      dnf:
        name: java-17-amazon-corretto
        state: present
        update_cache: true